on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    tools: 'composer:v2'

            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Install
                run: composer install

            -   name: Build
                run: php render

            # -   name: Configure GitHub Pages
            #     uses: actions/configure-pages@v3

            -   uses: actions/upload-artifact@v4
                with:
                    name: "custom-github-pages"
                    path: "./public"
                    retention-days: 1
                    overwrite: true

    deploy:
        name: Deploy
        needs: build
        permissions:
            contents: read
            pages: write
            id-token: write
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{steps.deployment.outputs.page_url}}
        steps:
            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4
                with:
                    artifact_name: "custom-github-pages"


